rating = [{text: "Best Years of Our Lives", size: 65},
{text: "Inherit the Wind", size: 53},
{text: "Godfather", size: 47},
{text: "Shawshank Redemption", size: 47},
{text: "Tom Jones", size: 43},
{text: "Gladiator", size: 43},
{text: "On the Waterfront", size: 42},
{text: "When We Were Kings", size: 41},
{text: "All About Eve", size: 40},
{text: "Ran", size: 39},
{text: "African Queen", size: 38},
{text: "Mister Roberts", size: 37},
{text: "Shall We Dance", size: 37},
{text: "Shadow of a Doubt", size: 36},
{text: "Roger & Me", size: 35},
{text: "Maltese Falcon", size: 34},
{text: "Band of Brothers", size: 34},
{text: "Godfather: Part II", size: 34},
{text: "It Happened One Night", size: 34},
{text: "Usual Suspects", size: 32},
{text: "Paths of Glory", size: 32},
{text: "Lifeboat", size: 32},
{text: "Rush", size: 32},
{text: "Modern Times", size: 31},
{text: "Philadelphia Story", size: 30},
{text: "Raging Bull", size: 30},
{text: "Chinatown", size: 28},
{text: "Happiness", size: 27},
{text: "Central Station (Central do Brasil)", size: 26},
{text: "Rear Window", size: 26},
{text: "Conversation", size: 24},
{text: "12 Angry Men", size: 24},
{text: "Schindler's List", size: 24},
{text: "To Be or Not to Be", size: 24},
{text: "Treasure of the Sierra Madre", size: 24},
{text: "Last Detail", size: 24},
{text: "City of God (Cidade de Deus)", size: 24},
{text: "Sunset Blvd. (a.k.a. Sunset Boulevard)", size: 23},
{text: "Smoke", size: 23},
{text: "Paris, Texas", size: 23},
{text: "Blood Simple", size: 23},
{text: "Diva", size: 22},
{text: "All Quiet on the Western Front", size: 22},
{text: "Seventh Seal, The (Sjunde inseglet, Det)", size: 22},
{text: "Seven Samurai (Shichinin no samurai)", size: 21},
{text: "Cool Hand Luke", size: 21},
{text: "Killing Fields", size: 21},
{text: "North by Northwest", size: 20},
{text: "Exotica", size: 20},
{text: "Harvey", size: 20},
{text: "M", size: 19},
{text: "Cinema Paradiso (Nuovo cinema Paradiso)", size: 19},
{text: "Strangers on a Train", size: 19},
{text: "One Flew Over the Cuckoo's Nest", size: 19},
{text: "Fargo", size: 19},
{text: "Pulp Fiction", size: 19},
{text: "Big Night", size: 18},
{text: "Third Man", size: 18},
{text: "Mutiny on the Bounty", size: 18},
{text: "Ideal Husband, An", size: 18},
{text: "Body Heat", size: 18},
{text: "General", size: 18},
{text: "You Can Count on Me", size: 18},
{text: "Rabbit-Proof Fence", size: 18},
{text: "Name of the Rose, The (Name der Rose, Der)", size: 17},
{text: "Touch of Evil", size: 16},
{text: "American Beauty", size: 16},
{text: "Dark Knight", size: 16},
{text: "Celluloid Closet", size: 16},
{text: "Casablanca", size: 16},
{text: "Star Wars: Episode V - The Empire Strikes Back", size: 16},
{text: "My Neighbor Totoro (Tonari no Totoro)", size: 16},
{text: "Stand and Deliver", size: 15},
{text: "Memento", size: 15},
{text: "Swingers", size: 15},
{text: "Mr. Smith Goes to Washington", size: 15},
{text: "Vertigo", size: 15},
{text: "Taxi Driver", size: 15},
{text: "Monty Python and the Holy Grail", size: 15},
{text: "Star Wars: Episode IV - A New Hope", size: 15}
];
